---
- name: Install Docker
  hosts: all
  become: yes
  tasks:
    - name: Install snapd
      apt:
        name: snapd
        state: present

    - name: Install Docker via snap
      snap:
        name: docker
        state: present
        channel: latest/stable
